import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useState } from 'react';
import { adminApi, type AdminSetting } from '../api/adminApi';
type Definition={group:string;label:string;help:string;type:'number'|'boolean';min?:number;max?:number;suffix?:string};
const definitions:Record<string,Definition>={
  'Applications.MaximumSectionChoices':{group:'Application settings',label:'Maximum course selections',help:'Maximum number of course sections an applicant can include in one application.',type:'number',min:1,max:10},
  'Documents.MaximumMegabytes':{group:'Document settings',label:'Maximum upload size',help:'Maximum size allowed for each resume or unofficial transcript.',type:'number',min:1,max:50,suffix:'MB'},
  'Development.ShowUserSwitcher':{group:'Local development',label:'Show demo user switcher',help:'Allows developers to switch among anonymized demonstration accounts.',type:'boolean'},
};
const definition=(key:string)=>definitions[key]!;
function SettingControl({setting}:{setting:AdminSetting}){
  const d=definition(setting.key);const client=useQueryClient();const[value,setValue]=useState(setting.value);const changed=value!==setting.value;const number=d.type==='number'?Number(value):undefined;const valid=d.type==='boolean'||(Number.isInteger(number)&&number!>=d.min!&&number!<=d.max!);
  const save=useMutation({mutationFn:()=>adminApi.updateSetting(setting.key,value),onSuccess:()=>client.invalidateQueries({queryKey:['admin-settings']})});
  return <article className="setting-card"><div><h3>{d.label}</h3><p>{d.help}</p></div>{d.type==='boolean'?<label className="setting-toggle"><input type="checkbox" checked={value==='true'} onChange={e=>setValue(String(e.target.checked))}/><span>{value==='true'?'On':'Off'}</span></label>:<label className="setting-number"><span className="visually-hidden">{d.label}</span><input type="number" min={d.min} max={d.max} value={value} onChange={e=>setValue(e.target.value)}/>{d.suffix&&<span>{d.suffix}</span>}</label>}{!valid&&<p className="field-error">Enter a value from {d.min} to {d.max}.</p>}<div className="setting-actions"><small>Last updated {new Date(setting.updatedAtUtc).toLocaleString()}</small><button className="button" disabled={!changed||!valid||save.isPending} onClick={()=>save.mutate()}>{save.isPending?'Saving…':'Save'}</button></div>{save.isSuccess&&<p className="success-message" role="status">Setting saved.</p>}{save.isError&&<div className="error-banner" role="alert">This setting could not be saved.</div>}</article>;
}
export function AdminSettingsFormPage(){const q=useQuery({queryKey:['admin-settings'],queryFn:adminApi.settings});if(q.isPending)return <p role="status">Loading settings…</p>;if(q.isError)return <div className="error-banner">Settings could not be loaded.</div>;const visible=q.data.filter(x=>definitions[x.key]&&(!x.isDevelopmentOnly||import.meta.env.DEV));const groups=[...new Set(visible.map(x=>definition(x.key).group))];return <div><header><h2>System settings</h2><p>Configure application behavior using validated administrative controls.</p></header>{groups.map(group=><section className="settings-group" key={group}><h3>{group}</h3>{group==='Local development'&&<div className="notice">These controls are available only during local development.</div>}<div className="settings-grid">{visible.filter(x=>definition(x.key).group===group).map(x=><SettingControl key={x.key} setting={x}/>)}</div></section>)}</div>}
