import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useState, type ReactNode } from 'react';
import { adminApi, type AdminPhase, type AdminSection, type AdminSetting, type AdminUser } from '../api/adminApi';

function State({ pending, error }: { pending:boolean; error:boolean }) { return pending ? <p role="status">Loading…</p> : error ? <div className="error-banner" role="alert">This administration data could not be loaded.</div> : null; }
function Table({ headers, children }: { headers:string[]; children:ReactNode }) { return <div className="table-scroll"><table><thead><tr>{headers.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{children}</tbody></table></div>; }

export function AdminApplicationsPage(){const q=useQuery({queryKey:['admin-applications'],queryFn:adminApi.applications});if(q.isPending||q.isError)return <State pending={q.isPending} error={q.isError}/>;return <Table headers={['Reference','Applicant','Program','Status','Choices','Submitted']}>{q.data.map(x=><tr key={x.id}><td>{x.reference}</td><td>{x.applicantName}</td><td>{x.program}</td><td>{x.state}</td><td>{x.choiceCount}</td><td>{x.submittedAtUtc?new Date(x.submittedAtUtc).toLocaleString():'—'}</td></tr>)}</Table>}
export function AdminApplicantsPage(){const q=useQuery({queryKey:['admin-applicants'],queryFn:adminApi.applicants});if(q.isPending||q.isError)return <State pending={q.isPending} error={q.isError}/>;return <Table headers={['Applicant','Email','University ID','Program','Profile','Applications']}>{q.data.map(x=><tr key={x.userId}><td>{x.displayName}</td><td>{x.email}</td><td>{x.universityId??'—'}</td><td>{x.program??'—'}</td><td>{x.profileComplete?'Complete':'Incomplete'}</td><td>{x.applicationCount}</td></tr>)}</Table>}

function SectionRow({initial,faculty,save,assign}:{initial:AdminSection;faculty:AdminUser[];save:(x:AdminSection)=>void;assign:(id:string,facultyId:string)=>void}){const [x,set]=useState(initial);return <tr><td>{x.courseCode}-{x.sectionNumber}<br/><small>{x.title}</small></td><td>{x.term}</td><td><input aria-label={`Positions for ${x.courseCode}`} type="number" min="0" value={x.availablePositions??''} onChange={e=>set({...x,availablePositions:e.target.value===''?null:Number(e.target.value)})}/></td><td><input aria-label={`Active ${x.courseCode}`} type="checkbox" checked={x.isActive} onChange={e=>set({...x,isActive:e.target.checked})}/></td><td><select aria-label={`Faculty for ${x.courseCode}`} value={x.facultyUserId??''} onChange={e=>{set({...x,facultyUserId:e.target.value||null});assign(x.id,e.target.value)}}><option value="">Unassigned</option>{faculty.map(f=><option key={f.id} value={f.id}>{f.displayName}</option>)}</select></td><td><button type="button" onClick={()=>save(x)}>Save</button></td></tr>}
export function AdminSectionsPage(){const client=useQueryClient();const sections=useQuery({queryKey:['admin-sections'],queryFn:adminApi.sections});const users=useQuery({queryKey:['admin-users'],queryFn:adminApi.users});const save=useMutation({mutationFn:adminApi.updateSection,onSuccess:()=>client.invalidateQueries({queryKey:['admin-sections']})});const assign=useMutation({mutationFn:({id,facultyId}:{id:string;facultyId:string})=>adminApi.assignFaculty(id,facultyId),onSuccess:()=>client.invalidateQueries({queryKey:['admin-sections']})});if(sections.isPending||users.isPending||sections.isError||users.isError)return <State pending={sections.isPending||users.isPending} error={sections.isError||users.isError}/>;const faculty=users.data.filter(x=>x.isActive&&x.roles.includes('Faculty'));return <Table headers={['Section','Term','Positions','Active','Faculty','Actions']}>{sections.data.map(x=><SectionRow key={x.id} initial={x} faculty={faculty} save={item=>save.mutate(item)} assign={(id,facultyId)=>assign.mutate({id,facultyId})}/>)}</Table>}

function PhaseRow({initial,save}:{initial:AdminPhase;save:(x:AdminPhase)=>void}){const[x,set]=useState(initial);return <tr><td>{x.name}</td><td>{x.program} / {x.term}</td><td><input type="datetime-local" value={x.opensAtUtc.slice(0,16)} onChange={e=>set({...x,opensAtUtc:new Date(e.target.value).toISOString()})}/></td><td><input type="datetime-local" value={x.closesAtUtc.slice(0,16)} onChange={e=>set({...x,closesAtUtc:new Date(e.target.value).toISOString()})}/></td><td><input type="checkbox" checked={x.isActive} onChange={e=>set({...x,isActive:e.target.checked})}/></td><td><button onClick={()=>save(x)}>Save</button></td></tr>}
export function AdminPhasesPage(){const client=useQueryClient();const q=useQuery({queryKey:['admin-phases'],queryFn:adminApi.phases});const save=useMutation({mutationFn:adminApi.updatePhase,onSuccess:()=>client.invalidateQueries({queryKey:['admin-phases']})});if(q.isPending||q.isError)return <State pending={q.isPending} error={q.isError}/>;return <Table headers={['Phase','Program / term','Opens','Closes','Active','Action']}>{q.data.map(x=><PhaseRow key={x.id} initial={x} save={item=>save.mutate(item)}/>)}</Table>}

function UserRow({initial,save}:{initial:AdminUser;save:(x:AdminUser)=>void}){const[x,set]=useState(initial);const roles=['Applicant','Faculty','Administrator'];return <tr><td>{x.displayName}</td><td>{x.email}</td><td><input type="checkbox" checked={x.isActive} onChange={e=>set({...x,isActive:e.target.checked})}/></td><td>{roles.map(role=><label key={role}><input type="checkbox" checked={x.roles.includes(role)} onChange={e=>set({...x,roles:e.target.checked?[...x.roles,role]:x.roles.filter(r=>r!==role)})}/> {role} </label>)}</td><td><button onClick={()=>save(x)}>Save</button></td></tr>}
export function AdminUsersPage(){const client=useQueryClient();const q=useQuery({queryKey:['admin-users'],queryFn:adminApi.users});const save=useMutation({mutationFn:adminApi.updateUser,onSuccess:()=>client.invalidateQueries({queryKey:['admin-users']})});if(q.isPending||q.isError)return <State pending={q.isPending} error={q.isError}/>;return <Table headers={['User','Email','Active','Roles','Action']}>{q.data.map(x=><UserRow key={x.id} initial={x} save={item=>save.mutate(item)}/>)}</Table>}

function SettingRow({initial,save}:{initial:AdminSetting;save:(x:AdminSetting)=>void}){const[x,set]=useState(initial);return <tr><td>{x.key}</td><td>{x.description??'—'}</td><td><input aria-label={`Value for ${x.key}`} value={x.value} onChange={e=>set({...x,value:e.target.value})}/></td><td>{x.isDevelopmentOnly?'Development':'All environments'}</td><td><button onClick={()=>save(x)}>Save</button></td></tr>}
export function AdminSettingsPage(){const client=useQueryClient();const q=useQuery({queryKey:['admin-settings'],queryFn:adminApi.settings});const save=useMutation({mutationFn:(x:AdminSetting)=>adminApi.updateSetting(x.key,x.value),onSuccess:()=>client.invalidateQueries({queryKey:['admin-settings']})});if(q.isPending||q.isError)return <State pending={q.isPending} error={q.isError}/>;return <Table headers={['Key','Description','Value','Scope','Action']}>{q.data.map(x=><SettingRow key={x.key} initial={x} save={item=>save.mutate(item)}/>)}</Table>}
export function AdminAuditPage(){const q=useQuery({queryKey:['admin-audit'],queryFn:adminApi.audit});if(q.isPending||q.isError)return <State pending={q.isPending} error={q.isError}/>;return <Table headers={['When','Action','Entity','Reference','Result','Correlation']}>{q.data.map(x=><tr key={x.id}><td>{new Date(x.occurredAtUtc).toLocaleString()}</td><td>{x.action}</td><td>{x.entityType}</td><td>{x.entityReference??'—'}</td><td>{x.result}</td><td>{x.correlationId}</td></tr>)}</Table>}
